sequenceDiagram
User->>App: Types name, email and password
loop Validate Email
    App->>App: Validate if email is valid
end
App->>Backend: Create user
Backend->>App: Returns Auth Token
App->>User: Redirect to home screen